export interface CountryItem {
  name: string;
  code: string;
  dialCode: string;
  maxLength: number;
}

export const COUNTRIES: CountryItem[] = [
  { name: "Bangladesh", code: "BD", dialCode: "880", maxLength: 10 },
  { name: "Afghanistan", code: "AF", dialCode: "93", maxLength: 9 },
  { name: "Albania", code: "AL", dialCode: "355", maxLength: 9 },
  { name: "Algeria", code: "DZ", dialCode: "213", maxLength: 9 },
  { name: "Andorra", code: "AD", dialCode: "376", maxLength: 9 },
  { name: "Angola", code: "AO", dialCode: "244", maxLength: 9 },
  { name: "Argentina", code: "AR", dialCode: "54", maxLength: 10 },
  { name: "Armenia", code: "AM", dialCode: "374", maxLength: 8 },
  { name: "Australia", code: "AU", dialCode: "61", maxLength: 9 },
  { name: "Austria", code: "AT", dialCode: "43", maxLength: 11 },
  { name: "Azerbaijan", code: "AZ", dialCode: "994", maxLength: 9 },
  { name: "Bahrain", code: "BH", dialCode: "973", maxLength: 8 },
  { name: "Belarus", code: "BY", dialCode: "375", maxLength: 9 },
  { name: "Belgium", code: "BE", dialCode: "32", maxLength: 9 },
  { name: "Bolivia", code: "BO", dialCode: "591", maxLength: 8 },
  { name: "Bosnia and Herzegovina", code: "BA", dialCode: "387", maxLength: 8 },
  { name: "Brazil", code: "BR", dialCode: "55", maxLength: 11 },
  { name: "Bulgaria", code: "BG", dialCode: "359", maxLength: 9 },
  { name: "Cambodia", code: "KH", dialCode: "855", maxLength: 9 },
  { name: "Cameroon", code: "CM", dialCode: "237", maxLength: 9 },
  { name: "Canada", code: "CA", dialCode: "1", maxLength: 10 },
  { name: "Chile", code: "CL", dialCode: "56", maxLength: 9 },
  { name: "China", code: "CN", dialCode: "86", maxLength: 11 },
  { name: "Colombia", code: "CO", dialCode: "57", maxLength: 10 },
  { name: "Croatia", code: "HR", dialCode: "385", maxLength: 9 },
  { name: "Cuba", code: "CU", dialCode: "53", maxLength: 8 },
  { name: "Czech Republic", code: "CZ", dialCode: "420", maxLength: 9 },
  { name: "Denmark", code: "DK", dialCode: "45", maxLength: 8 },
  { name: "Ecuador", code: "EC", dialCode: "593", maxLength: 9 },
  { name: "Egypt", code: "EG", dialCode: "20", maxLength: 10 },
  { name: "Ethiopia", code: "ET", dialCode: "251", maxLength: 9 },
  { name: "Finland", code: "FI", dialCode: "358", maxLength: 10 },
  { name: "France", code: "FR", dialCode: "33", maxLength: 9 },
  { name: "Georgia", code: "GE", dialCode: "995", maxLength: 9 },
  { name: "Germany", code: "DE", dialCode: "49", maxLength: 11 },
  { name: "Ghana", code: "GH", dialCode: "233", maxLength: 9 },
  { name: "Greece", code: "GR", dialCode: "30", maxLength: 10 },
  { name: "Guatemala", code: "GT", dialCode: "502", maxLength: 8 },
  { name: "Hungary", code: "HU", dialCode: "36", maxLength: 9 },
  { name: "India", code: "IN", dialCode: "91", maxLength: 10 },
  { name: "Indonesia", code: "ID", dialCode: "62", maxLength: 12 },
  { name: "Iran", code: "IR", dialCode: "98", maxLength: 10 },
  { name: "Iraq", code: "IQ", dialCode: "964", maxLength: 10 },
  { name: "Ireland", code: "IE", dialCode: "353", maxLength: 9 },
  { name: "Israel", code: "IL", dialCode: "972", maxLength: 9 },
  { name: "Italy", code: "IT", dialCode: "39", maxLength: 10 },
  { name: "Japan", code: "JP", dialCode: "81", maxLength: 10 },
  { name: "Jordan", code: "JO", dialCode: "962", maxLength: 9 },
  { name: "Kazakhstan", code: "KZ", dialCode: "7", maxLength: 10 },
  { name: "Kenya", code: "KE", dialCode: "254", maxLength: 9 },
  { name: "Kuwait", code: "KW", dialCode: "965", maxLength: 8 },
  { name: "Kyrgyzstan", code: "KG", dialCode: "996", maxLength: 9 },
  { name: "Lebanon", code: "LB", dialCode: "961", maxLength: 8 },
  { name: "Libya", code: "LY", dialCode: "218", maxLength: 9 },
  { name: "Malaysia", code: "MY", dialCode: "60", maxLength: 10 },
  { name: "Mexico", code: "MX", dialCode: "52", maxLength: 10 },
  { name: "Morocco", code: "MA", dialCode: "212", maxLength: 9 },
  { name: "Myanmar", code: "MM", dialCode: "95", maxLength: 10 },
  { name: "Nepal", code: "NP", dialCode: "977", maxLength: 10 },
  { name: "Netherlands", code: "NL", dialCode: "31", maxLength: 9 },
  { name: "New Zealand", code: "NZ", dialCode: "64", maxLength: 9 },
  { name: "Nigeria", code: "NG", dialCode: "234", maxLength: 10 },
  { name: "Norway", code: "NO", dialCode: "47", maxLength: 8 },
  { name: "Oman", code: "OM", dialCode: "968", maxLength: 8 },
  { name: "Pakistan", code: "PK", dialCode: "92", maxLength: 10 },
  { name: "Palestine", code: "PS", dialCode: "970", maxLength: 9 },
  { name: "Panama", code: "PA", dialCode: "507", maxLength: 8 },
  { name: "Peru", code: "PE", dialCode: "51", maxLength: 9 },
  { name: "Philippines", code: "PH", dialCode: "63", maxLength: 10 },
  { name: "Poland", code: "PL", dialCode: "48", maxLength: 9 },
  { name: "Portugal", code: "PT", dialCode: "351", maxLength: 9 },
  { name: "Qatar", code: "QA", dialCode: "974", maxLength: 8 },
  { name: "Romania", code: "RO", dialCode: "40", maxLength: 9 },
  { name: "Russia", code: "RU", dialCode: "7", maxLength: 10 },
  { name: "Saudi Arabia", code: "SA", dialCode: "966", maxLength: 9 },
  { name: "Serbia", code: "RS", dialCode: "381", maxLength: 9 },
  { name: "Singapore", code: "SG", dialCode: "65", maxLength: 8 },
  { name: "South Africa", code: "ZA", dialCode: "27", maxLength: 9 },
  { name: "South Korea", code: "KR", dialCode: "82", maxLength: 10 },
  { name: "Spain", code: "ES", dialCode: "34", maxLength: 9 },
  { name: "Sri Lanka", code: "LK", dialCode: "94", maxLength: 9 },
  { name: "Sudan", code: "SD", dialCode: "249", maxLength: 9 },
  { name: "Sweden", code: "SE", dialCode: "46", maxLength: 9 },
  { name: "Switzerland", code: "CH", dialCode: "41", maxLength: 9 },
  { name: "Syria", code: "SY", dialCode: "963", maxLength: 9 },
  { name: "Taiwan", code: "TW", dialCode: "886", maxLength: 9 },
  { name: "Tajikistan", code: "TJ", dialCode: "992", maxLength: 9 },
  { name: "Tanzania", code: "TZ", dialCode: "255", maxLength: 9 },
  { name: "Thailand", code: "TH", dialCode: "66", maxLength: 9 },
  { name: "Tunisia", code: "TN", dialCode: "216", maxLength: 8 },
  { name: "Turkey", code: "TR", dialCode: "90", maxLength: 10 },
  { name: "Turkmenistan", code: "TM", dialCode: "993", maxLength: 8 },
  { name: "Uganda", code: "UG", dialCode: "256", maxLength: 9 },
  { name: "Ukraine", code: "UA", dialCode: "380", maxLength: 9 },
  { name: "United Arab Emirates", code: "AE", dialCode: "971", maxLength: 9 },
  { name: "United Kingdom", code: "GB", dialCode: "44", maxLength: 10 },
  { name: "United States", code: "US", dialCode: "1", maxLength: 10 },
  { name: "Uruguay", code: "UY", dialCode: "598", maxLength: 8 },
  { name: "Uzbekistan", code: "UZ", dialCode: "998", maxLength: 9 },
  { name: "Venezuela", code: "VE", dialCode: "58", maxLength: 10 },
  { name: "Vietnam", code: "VN", dialCode: "84", maxLength: 10 },
  { name: "Yemen", code: "YE", dialCode: "967", maxLength: 9 },
  { name: "Zimbabwe", code: "ZW", dialCode: "263", maxLength: 9 },
];
