import { StyleSheet } from "react-native";
import { Colors } from "../../../constants/colors";

export const sharedStyles = StyleSheet.create({
  // Modal overlay
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
  },

  // Bottom sheet modal
  modalSheet: {
    backgroundColor: Colors.card,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingBottom: 32,
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: Colors.cardBorder,
    borderRadius: 2,
    alignSelf: "center",
    marginTop: 10,
    marginBottom: 4,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.cardBorder,
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  modalTitle: { color: Colors.text, fontSize: 16, fontWeight: "700" },
  modalLabel: { color: Colors.textSecondary, fontSize: 13, fontWeight: "600", marginBottom: 6 },
  modalInput: {
    backgroundColor: Colors.inputBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.inputBorder,
    color: Colors.text,
    fontSize: 14,
    padding: 14,
    marginBottom: 14,
  },
  modalPickerBtn: {
    backgroundColor: Colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
    padding: 14,
    marginBottom: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalPickerBtnText: { color: Colors.text, fontSize: 14 },

  // Buttons
  saveBtn: {
    backgroundColor: Colors.primary,
    borderRadius: 14,
    height: 52,
    justifyContent: "center",
    alignItems: "center",
  },
  saveBtnDisabled: { opacity: 0.6 },
  saveBtnText: { color: Colors.black, fontSize: 16, fontWeight: "700" },

  // Info card rows (used in Contact, TrainingLocations, address/website)
  infoCard: {
    marginHorizontal: 20,
    marginBottom: 10,
    backgroundColor: Colors.secondaryCard,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  infoIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: "rgba(209,255,0,0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  infoContent: { flex: 1, gap: 3 },
  infoLabel: { color: Colors.textSecondary, fontSize: 12 },
  infoValue: { color: Colors.text, fontSize: 14, fontWeight: "600" },

  // Section headers
  sectionHeader: {
    color: Colors.text,
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0.3,
    marginHorizontal: 20,
    marginBottom: 12,
    marginTop: 8,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginRight: 20,
    marginBottom: 12,
    marginTop: 8,
    paddingBottom: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.cardBorder,
  },
  sectionAddBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(209,255,0,0.1)",
    borderWidth: 1,
    borderColor: "rgba(209,255,0,0.3)",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  sectionAddBtnText: { color: Colors.primary, fontSize: 13, fontWeight: "600" },

  // Empty state / add placeholder
  addPlaceholder: {
    marginHorizontal: 20,
    marginBottom: 14,
    paddingVertical: 28,
    paddingHorizontal: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(209,255,0,0.2)",
    backgroundColor: "rgba(209,255,0,0.03)",
    alignItems: "center",
    gap: 6,
  },
  addPlaceholderIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "rgba(209,255,0,0.1)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 6,
  },
  addPlaceholderTitle: { color: Colors.text, fontSize: 15, fontWeight: "700" },
  addPlaceholderText: { color: Colors.textMuted, fontSize: 13 },

  // Rating badge (used in FeaturedReviews + Header)
  ratingBadge: {
    backgroundColor: Colors.primary,
    borderRadius: 8,
    paddingVertical: 5,
    paddingHorizontal: 12,
  },
  ratingText: { color: Colors.black, fontSize: 12, fontWeight: "800" },

  // Review cards
  reviewCard: {
    marginHorizontal: 20,
    marginBottom: 10,
    backgroundColor: Colors.secondaryCard,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
    padding: 16,
  },
  reviewHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  reviewerName: { color: Colors.text, fontSize: 14, fontWeight: "600", flex: 1 },
  reviewComment: { color: Colors.textSecondary, fontSize: 13, lineHeight: 19 },
  reviewPickerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.cardBorder,
  },

  // Picker bottom sheets (day picker, social picker)
  pickerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.45)",
  },
  pickerSheet: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: Colors.card,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingBottom: 28,
  },
  pickerBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.cardBorder,
  },
  pickerDone: { color: Colors.primary, fontSize: 16, fontWeight: "700" },
  pickerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Colors.cardBorder,
  },
  pickerRowActive: { backgroundColor: "rgba(209,255,0,0.08)" },
  pickerRowText: { color: Colors.text, fontSize: 15 },
  pickerRowTextActive: { color: Colors.primary, fontWeight: "600" },
});
